import type { FactoryRow } from "@/lib/use-site-content";

export type FactoryImportRow = Omit<FactoryRow, "id" | "location">;

/** Workbook fallback while the matching Supabase migration is awaiting execution. */
export const FACTORY_SUPPLIER_IMPORT: FactoryImportRow[] = [
  {
    name: "PurPick",
    category: "Writing Instruments/ Pens",
    moq: "5000",
    sample_time: "Easy Designs 10 Days; Challenging Designs 15 Days",
    contact: "Wechat: zzy0930zzy",
    notes:
      "Pen manufacturer specializing in customizable writing instruments and pen components. Offers OEM/ODM production, including custom pen designs, colors, barrels, refills, and other components. Suitable for branded merchandise, promotional products, and custom stationery production.",
    website: null,
    sort_order: 1,
  },
  {
    name: "OEM 美肌化妆品工厂 (MG Cosmetics Factory)",
    category: "Beauty & Personal/ Skin Care",
    moq: "Skin Care (50kg) Makeup Depends",
    sample_time: "3 - 7 Days",
    contact: "Wechat: WDanny427 RedBook:",
    notes: "",
    website: null,
    sort_order: 2,
  },
  {
    name: "安琪",
    category: "Women's Footwear & Shoes (Winter Boots and Birkenstock styles)",
    moq: "50",
    sample_time: "3 Days - 1 Week",
    contact: "Wechat: y739469387 Redbook: 63083161645",
    notes:
      "Women's footwear manufacturer producing shearling boots (similar to UGGs), clogs, slippers, and casual shoes (Birkenstocks) in various materials, colors, and styles.",
    website: null,
    sort_order: 3,
  },
  {
    name: "江苏菲诗曼酒店用品有限公司 (Mianyang Yilainiya Hotel Supplies Co., Ltd.)",
    category: "Hospitality & Hotel Supplies & Linens & Guestroom Supplies",
    moq: "5000",
    sample_time: "25-30 Days with Logo (Without logo 3 days)",
    contact:
      "Wechat: wxid_ld0ez6m01qnu22 (Account name is Ding Ye 鼎业）RedBook: 27769631531 (Account name is ELENYA)",
    notes:
      "Hotel supplier offering customizable toiletries, linens, towels, bathrobes, slippers, and other guestroom amenities for hotels and hospitality businesses.",
    website: null,
    sort_order: 4,
  },
  {
    name: "Ens Toys (Huizhou) Co., Ltd",
    category: "Vinyl figures, plush toys, rubber ducks",
    moq: "500-2,000 pcs (varies by item)",
    sample_time: "Depends on style",
    contact: "ensfactory.en.alibaba.com",
    notes: "",
    website: "https://ensfactory.en.alibaba.com",
    sort_order: 5,
  },
  {
    name: "Sobling Jewelry",
    category: "Custom silver/fashion jewelry",
    moq: "10",
    sample_time: "Depends on style",
    contact: "sobling.jewelry",
    notes:
      "Explicitly markets to small brands/new businesses; no CAD required, they support with sketches",
    website: "https://sobling.jewelry",
    sort_order: 6,
  },
  {
    name: "Daily Accessory Limited",
    category: "Sterling silver, brass, stainless steel jewelry",
    moq: "30-50",
    sample_time: "Depends on style",
    contact: "info@daily-accessory.com;",
    notes: "",
    website: null,
    sort_order: 7,
  },
  {
    name: "Biorun Sock",
    category: "Custom/OEM socks",
    moq: "Low",
    sample_time: "Depends on style",
    contact: "socks@biorun.cc; Phone: +86-4008-068-021",
    notes:
      "19 yrs experience, has a dedicated production base (Ankang), still smaller-order friendly per FAQ",
    website: null,
    sort_order: 8,
  },
  {
    name: "Lion Paper Products",
    category: "Custom notebooks, journals, stationery",
    moq: "Depends on style",
    sample_time: "",
    contact: "WhatsApp: +86 137 5075 6354",
    notes: "Positioned as an accessible OEM partner for smaller stationery orders",
    website: null,
    sort_order: 9,
  },
  {
    name: "Casmb) 中科医疗美容仪器有限公司",
    category: "Beauty & Medical Equipment",
    moq: "1",
    sample_time: "3 Days",
    contact: "Wechat: gzzkym01 RedBook: 49316443807",
    notes:
      "Manufacturer of professional aesthetic and med-spa equipment, including facial, skincare, body contouring, and other beauty devices. Supports OEM/ODM customization.",
    website: null,
    sort_order: 10,
  },
  {
    name: "泽一鞋业",
    category: "Footwear & Shoes",
    moq: "300",
    sample_time: "7 - 14 Days",
    contact: "Wechat: Jack-L668",
    notes:
      "Full-service footwear manufacturer specializing in fashion and leather shoes for men and women. Produces sneakers, loafers, dress shoes, casual shoes, boots, and trend-driven footwear. Offers OEM/ODM services including product development, sampling, manufacturing, and packaging for private-label and established brands including Circle Cage (环洞), Jolly Onn, First Floor, Wanna Lab, 鹿三先生 (LUSAN), OAKMOO, 经典的ABB (The Engineer), Set for Life, Mr. Dandy, Roolrren Homme, Whistlehunter × Oto3, Interris, and Triple Black (3BLK).",
    website: null,
    sort_order: 11,
  },
  {
    name: "Ruoran",
    category: "Jewelry",
    moq: "1",
    sample_time: "12-15 Days",
    contact: "Wechat: RR15302752353",
    notes: "",
    website: null,
    sort_order: 12,
  },
  {
    name: "北地兰家具 / AVAN",
    category: "Furniture & High End Home Furnishings",
    moq: "Depends on style",
    sample_time: "Depends on style",
    contact: "WeChat: BDL13049120904",
    notes:
      "High-end furniture supplier specializing in Italian minimalist and light-luxury whole-home furniture and coordinated residential furnishing solutions. Typical Products: Sofas, dining tables & chairs, beds, cabinets, coffee tables, side tables, and other whole-home furniture.",
    website: null,
    sort_order: 13,
  },
  {
    name: "Caifede Candles (Qingdao, China)",
    category: "Scented candles",
    moq: "500",
    sample_time: "Depends on style",
    contact: "Phone/WhatsApp: (+86 135 0648 3595) Email: info@caifedecandles.com",
    notes:
      "20 years in business, works with fragrance houses like IFF and Symrise & Scented candles, soy candles, reed diffusers, candle holders, tealights",
    website: null,
    sort_order: 14,
  },
  {
    name: "Guangzhou Bearky Bag Co., Ltd.",
    category: "Cosmetic bags, backpacks, tote bags, travel bags",
    moq: "500",
    sample_time: "Depends on style",
    contact: "Phone/WhatsApp: (+86 139 2879 1997) Skype: sallypeng123",
    notes: "",
    website: null,
    sort_order: 15,
  },
  {
    name: "Sibottle (Arrant Enterprises Ltd.)",
    category: "Stainless steel water bottles, tumblers, mugs",
    moq: "1,000 pcs",
    sample_time: "5-10 days",
    contact: "sales@sibottle.com",
    notes: "14 yrs OEM/ODM drinkware, SEDEX/BSCI/ISO9001 certified, FDA & LFGB tested",
    website: null,
    sort_order: 16,
  },
  {
    name: "Kangde Silicone",
    category: "Silicone kitchenware, baby products, pet supplies",
    moq: "Low MOQ (confirm per item)",
    sample_time: "Depends on style",
    contact: "sales@kangdesilicone.com",
    notes: "",
    website: null,
    sort_order: 17,
  },
  {
    name: "Winnerpak",
    category: "Jewelry boxes, gift boxes, packaging displays",
    moq: "500 pcs (boxes), 100 pcs (displays)",
    sample_time: "Depends on style",
    contact: "winnerpak@winnerpak.com WeChat: +86 189 2273 8146",
    notes: "34 yrs in jewelry/gift packaging, clients include Chow Tai Fook, Agatha, Thomas Sabo",
    website: null,
    sort_order: 18,
  },
  {
    name: "Heappy Eyewear",
    category: "Sunglasses, optical frames, blue light glasses",
    moq: "600 pcs (custom logo); 12-20 pcs (stock)",
    sample_time: "7 days (samples); 45-90 days (bulk, by material)",
    contact: "heappy.com/contact-us",
    notes: "20+ yrs, CE/FDA/BSCI compliant, 300+ workers",
    website: "https://heappy.com/contact-us",
    sort_order: 19,
  },
  {
    name: "Hucai Sportswear",
    category: "Gym clothing, tracksuits, activewear",
    moq: "Low MOQ (confirm per style)",
    sample_time: "Depends on style",
    contact: "Email: admin@hcsportswear.com; WhatsApp: +86 136 0233 8395",
    notes: "25 yrs sportswear OEM/ODM, Dongguan-based",
    website: null,
    sort_order: 20,
  },
  {
    name: "Plushtoysmfg",
    category: "Custom plush toys, pet plush toys",
    moq: "500 pcs",
    sample_time: "Depends on style",
    contact: "info@plushtoysmfg.com; WhatsApp/Phone: +86 157 0768 2483",
    notes: "10 yrs experience, Dongguan, mainly serves US/EU importers",
    website: null,
    sort_order: 21,
  },
  {
    name: "Hishell (Shenzhen Gobay Electronics)",
    category: "Phone cases, cellphone stands, AirPods/AirTags cases",
    moq: "Low MOQ (confirm per style)",
    sample_time: "Depends on style",
    contact: "hedy@hishell.com; Phone: +86-755-8366-5688; WhatsApp: +86 135 1099 8166",
    notes: "18 yrs phone accessory manufacturer, Shenzhen",
    website: null,
    sort_order: 22,
  },
  {
    name: "Galink Ltd",
    category: "Custom towels (bath, hand, golf, beach), blankets",
    moq: "50",
    sample_time: "3-5 days No Logo",
    contact: "info@galinkltd.com; Phone: +86 181 2008 1396",
    notes: "14+ yrs OEM/ODM, GRS & Sedex certified, Suzhou",
    website: null,
    sort_order: 23,
  },
  {
    name: "Speck Yoga Fitness Group",
    category: "Yoga mats, yoga blocks/towels, fitness equipment",
    moq: "Low",
    sample_time: "Depends on style",
    contact: "phone: +86 21 5920 5922",
    notes: "25+ yrs, 50-person design team, Shanghai, works with Walmart/IKEA/Target-scale clients",
    website: null,
    sort_order: 24,
  },
  {
    name: "Weijun Toy Co., Ltd.",
    category: "Action figures, vinyl toys, plush, blind boxes",
    moq: "500 pcs (plush); 3,000 (OEM plastic)",
    sample_time: "Depends on style",
    contact: "Phone: (86) 28-2639 8888; Email: info@weijuntoy.com; WhatsApp/WeChat: +86 150 2159",
    notes: "45 injection molding machines listed, CE/ISO/EN71|",
    website: null,
    sort_order: 25,
  },
  {
    name: "飞鸾鞋业",
    category: "Summer Shoes",
    moq: "100-300",
    sample_time: "7-10 Days",
    contact: "Wechat: tts_sang",
    notes: "时装高跟鞋 单鞋 凉鞋 高跟凉拖",
    website: null,
    sort_order: 26,
  },
];
