/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as LightRouteRouteImport } from './routes/light/route'
import { Route as MembersRouteImport } from './routes/members'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as LightIndexRouteImport } from './routes/light/index'
import { Route as LightAboutRouteImport } from './routes/light/about'
import { Route as LightEventsRouteImport } from './routes/light/events'
import { Route as LightGuestsRouteImport } from './routes/light/guests'
import { Route as LightMembersRouteImport } from './routes/light/members'
import { Route as LightPartnersRouteImport } from './routes/light/partners'
import { Route as LightProjectsRouteImport } from './routes/light/projects'
import { Route as LightQaRouteImport } from './routes/light/qa'
import { Route as MemberMemberIdRouteImport } from './routes/member.$memberId'
import { Route as NfcTokenRouteImport } from './routes/nfc.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const LightRouteRoute = LightRouteRouteImport.update({
  id: '/light',
  path: '/light',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LightIndexRoute = LightIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LightRouteRoute,
} as any)
const LightAboutRoute = LightAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LightRouteRoute,
} as any)
const LightEventsRoute = LightEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LightRouteRoute,
} as any)
const LightGuestsRoute = LightGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => LightRouteRoute,
} as any)
const LightMembersRoute = LightMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LightRouteRoute,
} as any)
const LightPartnersRoute = LightPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => LightRouteRoute,
} as any)
const LightProjectsRoute = LightProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LightRouteRoute,
} as any)
const LightQaRoute = LightQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => LightRouteRoute,
} as any)
const MemberMemberIdRoute = MemberMemberIdRouteImport.update({
  id: '/member/$memberId',
  path: '/member/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcTokenRoute = NfcTokenRouteImport.update({
  id: '/nfc/$token',
  path: '/nfc/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/light': typeof LightRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/events': typeof EventsRoute
  '/guests': typeof GuestsRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/qa': typeof QaRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/light/about': typeof LightAboutRoute
  '/light/events': typeof LightEventsRoute
  '/light/guests': typeof LightGuestsRoute
  '/light/members': typeof LightMembersRoute
  '/light/partners': typeof LightPartnersRoute
  '/light/projects': typeof LightProjectsRoute
  '/light/qa': typeof LightQaRoute
  '/member/$memberId': typeof MemberMemberIdRoute
  '/nfc/$token': typeof NfcTokenRoute
  '/light/': typeof LightIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/events': typeof EventsRoute
  '/guests': typeof GuestsRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/qa': typeof QaRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/light/about': typeof LightAboutRoute
  '/light/events': typeof LightEventsRoute
  '/light/guests': typeof LightGuestsRoute
  '/light/members': typeof LightMembersRoute
  '/light/partners': typeof LightPartnersRoute
  '/light/projects': typeof LightProjectsRoute
  '/light/qa': typeof LightQaRoute
  '/member/$memberId': typeof MemberMemberIdRoute
  '/nfc/$token': typeof NfcTokenRoute
  '/light': typeof LightIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/light': typeof LightRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/events': typeof EventsRoute
  '/guests': typeof GuestsRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/qa': typeof QaRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/waitlist': typeof WaitlistRoute
  '/light/about': typeof LightAboutRoute
  '/light/events': typeof LightEventsRoute
  '/light/guests': typeof LightGuestsRoute
  '/light/members': typeof LightMembersRoute
  '/light/partners': typeof LightPartnersRoute
  '/light/projects': typeof LightProjectsRoute
  '/light/qa': typeof LightQaRoute
  '/member/$memberId': typeof MemberMemberIdRoute
  '/nfc/$token': typeof NfcTokenRoute
  '/light/': typeof LightIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/light'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/events'
    | '/guests'
    | '/members'
    | '/onboarding'
    | '/partners'
    | '/projects'
    | '/qa'
    | '/resources'
    | '/sitemap.xml'
    | '/waitlist'
    | '/light/about'
    | '/light/events'
    | '/light/guests'
    | '/light/members'
    | '/light/partners'
    | '/light/projects'
    | '/light/qa'
    | '/member/$memberId'
    | '/nfc/$token'
    | '/light/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/events'
    | '/guests'
    | '/members'
    | '/onboarding'
    | '/partners'
    | '/projects'
    | '/qa'
    | '/resources'
    | '/sitemap.xml'
    | '/waitlist'
    | '/light/about'
    | '/light/events'
    | '/light/guests'
    | '/light/members'
    | '/light/partners'
    | '/light/projects'
    | '/light/qa'
    | '/member/$memberId'
    | '/nfc/$token'
    | '/light'
  id:
    | '__root__'
    | '/'
    | '/light'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/events'
    | '/guests'
    | '/members'
    | '/onboarding'
    | '/partners'
    | '/projects'
    | '/qa'
    | '/resources'
    | '/sitemap.xml'
    | '/waitlist'
    | '/light/about'
    | '/light/events'
    | '/light/guests'
    | '/light/members'
    | '/light/partners'
    | '/light/projects'
    | '/light/qa'
    | '/member/$memberId'
    | '/nfc/$token'
    | '/light/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LightRouteRoute: typeof LightRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BusinessesRoute: typeof BusinessesRoute
  EventsRoute: typeof EventsRoute
  GuestsRoute: typeof GuestsRoute
  MembersRoute: typeof MembersRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  ProjectsRoute: typeof ProjectsRoute
  QaRoute: typeof QaRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WaitlistRoute: typeof WaitlistRoute
  MemberMemberIdRoute: typeof MemberMemberIdRoute
  NfcTokenRoute: typeof NfcTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light': {
      id: '/light'
      path: '/light'
      fullPath: '/light'
      preLoaderRoute: typeof LightRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light/': {
      id: '/light/'
      path: '/'
      fullPath: '/light/'
      preLoaderRoute: typeof LightIndexRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/light/about': {
      id: '/light/about'
      path: '/about'
      fullPath: '/light/about'
      preLoaderRoute: typeof LightAboutRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/light/events': {
      id: '/light/events'
      path: '/events'
      fullPath: '/light/events'
      preLoaderRoute: typeof LightEventsRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/light/guests': {
      id: '/light/guests'
      path: '/guests'
      fullPath: '/light/guests'
      preLoaderRoute: typeof LightGuestsRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/light/members': {
      id: '/light/members'
      path: '/members'
      fullPath: '/light/members'
      preLoaderRoute: typeof LightMembersRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/light/partners': {
      id: '/light/partners'
      path: '/partners'
      fullPath: '/light/partners'
      preLoaderRoute: typeof LightPartnersRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/light/projects': {
      id: '/light/projects'
      path: '/projects'
      fullPath: '/light/projects'
      preLoaderRoute: typeof LightProjectsRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/light/qa': {
      id: '/light/qa'
      path: '/qa'
      fullPath: '/light/qa'
      preLoaderRoute: typeof LightQaRouteImport
      parentRoute: typeof LightRouteRoute
    }
    '/member/$memberId': {
      id: '/member/$memberId'
      path: '/member/$memberId'
      fullPath: '/member/$memberId'
      preLoaderRoute: typeof MemberMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc/$token': {
      id: '/nfc/$token'
      path: '/nfc/$token'
      fullPath: '/nfc/$token'
      preLoaderRoute: typeof NfcTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LightRouteRouteChildren {
  LightAboutRoute: typeof LightAboutRoute
  LightEventsRoute: typeof LightEventsRoute
  LightGuestsRoute: typeof LightGuestsRoute
  LightMembersRoute: typeof LightMembersRoute
  LightPartnersRoute: typeof LightPartnersRoute
  LightProjectsRoute: typeof LightProjectsRoute
  LightQaRoute: typeof LightQaRoute
  LightIndexRoute: typeof LightIndexRoute
}

const LightRouteRouteChildren: LightRouteRouteChildren = {
  LightAboutRoute: LightAboutRoute,
  LightEventsRoute: LightEventsRoute,
  LightGuestsRoute: LightGuestsRoute,
  LightMembersRoute: LightMembersRoute,
  LightPartnersRoute: LightPartnersRoute,
  LightProjectsRoute: LightProjectsRoute,
  LightQaRoute: LightQaRoute,
  LightIndexRoute: LightIndexRoute,
}

const LightRouteRouteWithChildren = LightRouteRoute._addFileChildren(
  LightRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LightRouteRoute: LightRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BusinessesRoute: BusinessesRoute,
  EventsRoute: EventsRoute,
  GuestsRoute: GuestsRoute,
  MembersRoute: MembersRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  ProjectsRoute: ProjectsRoute,
  QaRoute: QaRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WaitlistRoute: WaitlistRoute,
  MemberMemberIdRoute: MemberMemberIdRoute,
  NfcTokenRoute: NfcTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
